In [1]:
import pandas as pd
import numpy as np
import requests #api
import json #json file
from datetime import datetime

import matplotlib.pyplot as plt
from scipy.stats import linregress #stastistical analysis

from pathlib import Path #reading csv - connecting to the csv merges mac and windows

from sodapy import Socrata #used for cdc API fetch

## COVID-19 Case Surveillance Public Use Data with Geography

In [2]:
#https://data.cdc.gov/Case-Surveillance/COVID-19-Case-Surveillance-Public-Use-Data-with-Ge/n8mc-b4w4
case_surv_url = "https://data.cdc.gov/resource/n8mc-b4w4.json?"
case_surv_data = requests.get(case_surv_url).json()

case_surv_df = pd.DataFrame(case_surv_data)
#case_surv_df

In [3]:
CA_case_surv_url = "https://data.cdc.gov/resource/n8mc-b4w4.json?res_state=CA"
CA_case_surv_data = requests.get(case_surv_url).json()

CA_case_surv_df = pd.DataFrame(CA_case_surv_data)
#CA_case_surv_df

In [4]:
#CA_case_surv_df["death_yn"].unique()

In [5]:
#CA_case_surv_df["hosp_yn"].unique()

In [6]:
#CA_case_surv_df["hosp_yn"].value_counts()

In [7]:
client = Socrata("data.cdc.gov",
                  "iwYpUxUglJyjEqOoTODioBzcV",
                  username="isabelmwork@gmail.com",
                  password="APIkey2023")
CA_case_surv_query = client.get("n8mc-b4w4", res_state="CA", limit=100000)
CA_case_surv_df = pd.DataFrame.from_records(CA_case_surv_query)

In [8]:
CA_case_surv_df.head()

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn,case_positive_specimen
0,2020-10,CA,06,SANTA CRUZ,06087,18 to 49 years,Male,Unknown,Hispanic/Latino,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,NaN
1,2022-02,CA,06,FRESNO,06019,0 - 17 years,Female,American Indian/Alaska Native,Hispanic/Latino,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN
2,2020-12,CA,06,ALAMEDA,06001,18 to 49 years,Female,American Indian/Alaska Native,Hispanic/Latino,0.0,Missing,Missing,Probable Case,Symptomatic,No,Missing,Missing,NaN,NaN
3,2022-12,CA,06,ORANGE,06059,18 to 49 years,Female,American Indian/Alaska Native,Hispanic/Latino,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN
4,2022-02,CA,06,STANISLAUS,06099,18 to 49 years,Female,American Indian/Alaska Native,Hispanic/Latino,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,NaN

In [9]:
CA_case_surv_df = CA_case_surv_df.sort_values(by=["res_county"])
CA_case_surv_df.head()

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn,case_positive_specimen
33903,2022-08,CA,06,ALAMEDA,06001,0 - 17 years,Male,White,Hispanic/Latino,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN
37403,2022-02,CA,06,ALAMEDA,06001,50 to 64 years,Male,White,Hispanic/Latino,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN
78143,2020-06,CA,06,ALAMEDA,06001,18 to 49 years,Female,NA,NA,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,NaN
87196,2020-06,CA,06,ALAMEDA,06001,18 to 49 years,Female,NA,NA,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN,NaN
6895,2020-11,CA,06,ALAMEDA,06001,50 to 64 years,Female,Unknown,Hispanic/Latino,NaN,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,NaN

In [10]:
CA_case_surv_df["res_county"] = CA_case_surv_df["res_county"].str.lower().str.capitalize()

In [11]:
CA_case_surv_df.head()

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn,case_positive_specimen
33903,2022-08,CA,06,Alameda,06001,0 - 17 years,Male,White,Hispanic/Latino,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN
37403,2022-02,CA,06,Alameda,06001,50 to 64 years,Male,White,Hispanic/Latino,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN
78143,2020-06,CA,06,Alameda,06001,18 to 49 years,Female,NA,NA,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,NaN
87196,2020-06,CA,06,Alameda,06001,18 to 49 years,Female,NA,NA,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN,NaN
6895,2020-11,CA,06,Alameda,06001,50 to 64 years,Female,Unknown,Hispanic/Latino,NaN,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,NaN

In [14]:
CA_case_surv_df[["year", "month"]] = CA_case_surv_df["case_month"].str.split("-", expand = True)

In [16]:
CA_case_surv_df.head()

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_onset_interval,...,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn,case_positive_specimen,year,month
33903,2022-08,CA,06,Alameda,06001,0 - 17 years,Male,White,Hispanic/Latino,NaN,...,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN,2022,08
37403,2022-02,CA,06,Alameda,06001,50 to 64 years,Male,White,Hispanic/Latino,NaN,...,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN,NaN,2022,02
78143,2020-06,CA,06,Alameda,06001,18 to 49 years,Female,NA,NA,0.0,...,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,NaN,2020,06
87196,2020-06,CA,06,Alameda,06001,18 to 49 years,Female,NA,NA,NaN,...,Missing,Laboratory-confirmed case,Unknown,No,Missing,Missing,NaN,NaN,2020,06
6895,2020-11,CA,06,Alameda,06001,50 to 64 years,Female,Unknown,Hispanic/Latino,NaN,...,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN,NaN,2020,11

In [17]:
#CA_case_surv_df.info()

In [18]:
CA_case_sel_df = CA_case_surv_df[["res_county", "case_month", "year", "month", "age_group", \
                                  "sex", "race", "ethnicity", "hosp_yn", "icu_yn", "death_yn", \
                                  "underlying_conditions_yn"]]

In [19]:
CA_case_sel_df.head()

,res_county,case_month,year,month,age_group,sex,race,ethnicity,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
33903,Alameda,2022-08,2022,08,0 - 17 years,Male,White,Hispanic/Latino,Missing,Missing,Missing,NaN
37403,Alameda,2022-02,2022,02,50 to 64 years,Male,White,Hispanic/Latino,Missing,Missing,Missing,NaN
78143,Alameda,2020-06,2020,06,18 to 49 years,Female,NA,NA,No,Missing,Missing,NaN
87196,Alameda,2020-06,2020,06,18 to 49 years,Female,NA,NA,No,Missing,Missing,NaN
6895,Alameda,2020-11,2020,11,50 to 64 years,Female,Unknown,Hispanic/Latino,No,Missing,Missing,NaN

In [20]:
#CA_case_sel_df.info()

In [21]:
CA_case_sel_df = CA_case_sel_df.rename(columns = {"res_county": "county", "case_month": "date"})

In [22]:
CA_case_sel_df.head()

,county,date,year,month,age_group,sex,race,ethnicity,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
33903,Alameda,2022-08,2022,08,0 - 17 years,Male,White,Hispanic/Latino,Missing,Missing,Missing,NaN
37403,Alameda,2022-02,2022,02,50 to 64 years,Male,White,Hispanic/Latino,Missing,Missing,Missing,NaN
78143,Alameda,2020-06,2020,06,18 to 49 years,Female,NA,NA,No,Missing,Missing,NaN
87196,Alameda,2020-06,2020,06,18 to 49 years,Female,NA,NA,No,Missing,Missing,NaN
6895,Alameda,2020-11,2020,11,50 to 64 years,Female,Unknown,Hispanic/Latino,No,Missing,Missing,NaN

In [23]:
#CA_case_sel_df = CA_case_sel_df.sort_values(by=["year"], ascending=True).sort_values(by=["county"], ascending=True)

In [24]:
#CA_case_sel_df = CA_case_sel_df.sort_values(by=["county"])

## Vaccine Data CA

In [25]:
#https://data.chhs.ca.gov/dataset/vaccine-progress-dashboard
CA_vax_path = Path("covid19vaccinesbycounty.csv")
CA_vax_df = pd.read_csv(CA_vax_path)
CA_vax_df.head()

,county,administered_date,total_doses,cumulative_total_doses,partially_vaccinated,total_partially_vaccinated,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,up_to_date_count,cumulative_up_to_date_count
0,Alameda,2020-01-05,0,0,0,0,0,0,0,0,NaN,0,0
1,Alameda,2020-07-27,0,0,0,0,0,0,0,0,NaN,0,0
2,Alameda,2020-07-29,0,1,0,1,0,0,0,1,NaN,0,0
3,Alameda,2020-07-30,0,1,0,1,0,0,0,1,NaN,0,0
4,Alameda,2020-07-31,0,1,0,1,0,0,0,1,NaN,0,0

## COVID-19 Vaccines Up to Date Status

In [26]:
#https://data.cdc.gov/Public-Health-Surveillance/Rates-of-COVID-19-Cases-or-Deaths-by-Age-Group-and/3rge-nu2a
#client = Socrata("data.cdc.gov",
                  #"iwYpUxUglJyjEqOoTODioBzcV",
                  #username="isabelmwork@gmail.com",
                  #password="APIkey2023")
#CA_vaccine_query = client.get("9b5z-wnve", Location="CA", limit=100000)

In [27]:
#CA_vaccine_df = pd.DataFrame.from_records(CA_vaccine_query)
#CA_vaccine_df

In [28]:
#CA_vaccine_df["date"].value_counts()